# https://vadosware.io/post/zero-to-continuous-integrated-testing-a-haskell-project-with-gitlab/
# Caching! https://docs.gitlab.com/ee/ci/yaml/README.html#cache

# this should match stack.yaml
# image: fpco/stack-build:lts-13.7
image: haskell:8


before_script:
  - apt-get update -y
  - apt-get install libpq-dev -y


# these stages should match the pipeline
stages:
  - build
  - test
  - deploy


build:
  stage: build
  script:
    - cd server
    - stack setup
    - stack build --only-dependencies
    - stack build

test:
  stage: test
  script:
    - cd server
    - stack test

deploy:
  stage: deploy
  script:
    - echo "DEPLOY - it looks like nothing is cached between these"
    # - stack image container
    # - docker run -it timely /usr/local/bin/timely


# before_script:
  # - apt-get update
  # - apt-get install make xz-utils

cache:
  paths:
    - .stack
    - .stack-work

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"
