# this should match stack.yaml
image: fpco/stack-build:lts-13.7


# these stages should match the pipeline
stages:
  - build
  - test
  - deploy

# before_script:
  # - apt-get update
  # - apt-get install make xz-utils

build:
  stage: build
  script:
    - cd server
    - make build

test:
  stage: test
  script:
    - cd server
    - make test

deploy:
  stage: deploy
  script:
    - echo "DEPLOY"



# Caching! https://docs.gitlab.com/ee/ci/yaml/README.html#cache
