image: fpco/stack-build:lts-13.2

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - cd server
    - make build

test:
  stage: test
  script:
    - cd server
    - make test

deploy:
  stage: deploy
  script:
    - echo "DEPLOY"
