version: "3"
services:

  api:
    image: timely-api:latest
    ports:
    - "3001:3002"
    environment:
      - PORT=3002
      - POSTGRES=postgresql://postgres@postgres:5432
      - AMQP=amqp://guest:guest@amqp:5672

  postgres:
    image: postgres
    ports:
    - "5432:5432"

  amqp:
    image: rabbitmq:3-management
    ports:
    - "5672:5672"
    - "15672:15672"
