apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-example
spec:
  schedule: '* * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob-example
              image: busybox
              args:
                - /bin/sh
                - '-c'
                - echo "This is an example cronjob running $(date)"
          restartPolicy: OnFailure
