apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 3002
    protocol: TCP
  type: NodePort
  selector:
    app: api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  namespace: default
spec:
  revisionHistoryLimit: 2
  replicas: 2
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
      - name: api
        image: registry.gitlab.com/timely-advance/timely:$VERSION
        args:
        - /usr/local/bin/timely
        - api
        ports:
        - containerPort: 3002
        env:
        - name: AMQP
          value: amqp://guest:guest@amqp:5672
        - name: PORT
          value: "3002"
        - name: POSTGRES
          value: postgresql://postgres@postgres:5432
        - name: APP_ENDPOINT
          value: https://test.timelyadvance.com
        - name: PLAID_WEBHOOK
          value: https://test.timelyadvance.com/v1/webhooks/plaid
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 15
          periodSeconds: 15
