apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: schedule-advance-collect
spec:
  schedule: '0 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: gitlab-docker-registry
          containers:
            - args:
              - /usr/local/bin/timely
              - schedule-advance-collect
              env:
              - name: AMQP
                value: amqp://guest:guest@amqp:5672
              - name: POSTGRES
                value: postgresql://postgres@postgres:5432
              name: schedule-advance-collect
              image: registry.gitlab.com/timely-advance/timely:0.1.3
          restartPolicy: OnFailure
