apiVersion: v1
kind: Service
metadata:
  name: web-static
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: web-static
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-static
spec:
  selector:
    matchLabels:
      app: web-static
  revisionHistoryLimit: 2
  replicas: 1
  template:
    metadata:
      labels:
        app: web-static
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: web-static
          image: registry.gitlab.com/timely-advance/timely/web:$VERSION
          ports:
          - containerPort: 80
