apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: work-advance-send
  name: work-advance-send
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: work-advance-send
    spec:
      containers:
      - args:
        - /usr/local/bin/timely
        - work-advance-send
        env:
        - name: AMQP
          value: amqp://guest:guest@amqp:5672
        - name: POSTGRES
          value: postgresql://postgres@postgres:5432
        image: registry.gitlab.com/timely-advance/timely
        name: work-advance-send
        resources: {}
      restartPolicy: Always
status: {}
