apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: work-advance-collect
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy: {}
  template:
    metadata:
      labels:
        name: work-advance-collect
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
      - args:
        - /usr/local/bin/timely
        - work-advance-collect
        env:
        - name: AMQP
          value: amqp://guest:guest@amqp:5672
        - name: POSTGRES
          value: postgresql://postgres@postgres:5432
        - name: APP_ENDPOINT
          value: http://test.timelyadvance.com/app/
        image: registry.gitlab.com/timely-advance/timely:$VERSION
        name: work-advance-collect
      restartPolicy: Always
