name:                server
version:             0.1.0.0
github:              "seanhess/server"
license:             BSD3
author:              "Sean Hess"
maintainer:          "seanhess@gmail.com"
copyright:           "Orbital Labs"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/seanhess/server#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- beam-core
- beam-migrate
- beam-postgres
- mtl
- servant
- servant-server
- string-conversions
- stm
- text
- wai
- warp

library:
  source-dirs: src

executables:
  server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - server

tests:
  server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - server
