name:                server
version:             0.1.0.0
github:              "seanhess/server"
license:             BSD3
author:              "Sean Hess"
maintainer:          "seanhess@gmail.com"
copyright:           "Orbital Labs"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/seanhess/server#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-pretty
- amqp
- amqp-worker
- bytestring
- elm-export
- envy
- exceptions
- http-media
- http-client
- http-client-tls
- http-types
- jose
- mtl
- monad-control
- monad-logger
- random
- pretty-show
- resource-pool
- servant
- servant-server
- servant-elm
- servant-client
- servant-auth
- servant-auth-server
- selda
- selda-postgresql
- selda-sqlite
- string-conversions
- stm
- transformers-base
- time
- twilio
- text
- uuid
- unix
- wai
- wai-extra
- warp
- warp-tls


# default-extensions:
# - DataKinds
# - DeriveGeneric
# - FlexibleInstances
# - FlexibleContexts
# - GADTs
# - MultiParamTypeClasses
# - KindSignatures
# - OverloadedStrings
# - OverloadedLabels
# - RecordWildCards
# - ScopedTypeVariables
# - DuplicateRecordFields
# - TypeFamilies
# - TypeOperators


ghc-options:
- -W

library:
  source-dirs:
    - src
    - bank
    - underwrite
    - accounts
    - advances
    - auth
    - evaluate
    - client
    - transfers

executables:
  server-exe:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - server

tests:
  server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty
    - tasty-hunit
    - server
