name:                timely
version:             0.2.0
github:              "seanhess/server"
license:             BSD3
author:              "Sean Hess"
maintainer:          "seanhess@gmail.com"
copyright:           "Orbital Labs"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/seanhess/server#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-pretty
- amqp
- amqp-worker
- async
- async-timer
- base64-bytestring
- bytestring
- containers
- cryptonite
- memory
- data-default
- datamodel
- envy
- exceptions
- filepath
- http-api-data
- http-client
- http-client-tls
- http-media
- http-types
- jose
- lens
- monad-control
- monad-logger
- monad-loops
- mtl
- pretty-show
- random
- resource-pool
- retry
- selda
- selda-postgresql
- selda-sqlite
- servant
- servant-auth
- servant-auth-server
- servant-client
- servant-client-core
- servant-server
- simple-effects
- stm
- string-conversions
- text
- time
- transformers
- transformers-base
- twilio
- unix
- uuid
- unordered-containers
- wai
- wai-extra
- warp
- warp-tls
- wreq
- xml-conduit
- xml-conduit-writer
- xml-types


# I'm not sure this is a good idea
# default-extensions:
# - DataKinds
# - DeriveGeneric
# - FlexibleInstances
# - FlexibleContexts
# - GADTs
# - MultiParamTypeClasses
# - KindSignatures
# - OverloadedStrings
# - OverloadedLabels
# - RecordWildCards
# - ScopedTypeVariables
# - DuplicateRecordFields
# - TypeFamilies
# - TypeOperators


ghc-options:
- -W
- -optP-Wno-nonportable-include-path # https://github.com/commercialhaskell/stack/issues/3918

library:
  source-dirs:
    - src
    - bank
    - underwrite
    - accounts
    - advances
    - auth
    - transfers

executables:
  timely:
    main:                Main.hs
    source-dirs:
    - .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - timely

  timely-test:
    main:                Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - timely
    - tasty
    - tasty-hunit
    - random-strings
    - here
