# This configures the routing for our application 
# SSL Redirect: https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/tasks/ssl_redirect/
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  # must be in the same namespace as the app
  namespace: default

  # These are arbitrary
  name: timely-ingress
  labels:
    app: timely-ingress

  annotations:
      # required fields
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing

      # associate with SSL certificate
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:575625783736:certificate/f0dce948-18f5-495b-a4c3-233cf39281b0

      # config
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
spec:
  rules:
    - host: echo.timelyadvance.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: echoserver
              servicePort: 80
    - host: api.timelyadvance.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: api
              servicePort: 80

     # test.timelyadvance.com and anything will redirect here, as it has no host
    - http:
        paths:
         - path: /*
           backend:
             serviceName: ssl-redirect
             servicePort: use-annotation
         - path: /echo/*
           backend:
             serviceName: echoserver
             servicePort: 80
         - path: /v1/*
           backend:
             serviceName: api
             servicePort: 80
         - path: /health
           backend:
             serviceName: api
             servicePort: 80
         - path: /debug
           backend:
             serviceName: api
             servicePort: 80
         - path: /*
           backend:
             serviceName: web-static
             servicePort: 80
